'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SQLDataBasesBackup.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property PKUNZIP() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PKUNZIP", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property PKZIP() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PKZIP", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Rar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Rar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @ECHO OFF
        ''':BEGIN
        '''ECHO Hey there! This process to Restart sql servises ... 
        ''':END
        '''@ECHO OFF
        ''':BEGIN
        '''ECHO  Powered By Ahmed Rashwan-Ocean Soft technical support!
        ''':END
        '''color 1b
        '''net stop MSSQLSERVER /y
        '''net stop SQLSERVERAGENT /y
        '''net stop SQLBrowser /y
        '''net start MSSQLSERVER /y
        '''net Start SQLSERVERAGENT /y
        '''net Start SQLBrowser /y.
        '''</summary>
        Public ReadOnly Property RestartServ() As String
            Get
                Return ResourceManager.GetString("RestartServ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CreateObject(&quot;Wscript.Shell&quot;).Run &quot;&quot;&quot;&quot; &amp; WScript.Arguments(0) &amp; &quot;&quot;&quot;&quot;, 0, False
        '''
        '''.
        '''</summary>
        Public ReadOnly Property silentmode() As String
            Get
                Return ResourceManager.GetString("silentmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wscript.exe &quot;E:\baktools\silentmode.vbs&quot; &quot;E:\baktools\backup.bat&quot;
        '''
        '''.
        '''</summary>
        Public ReadOnly Property sm() As String
            Get
                Return ResourceManager.GetString("sm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @ECHO OFF
        ''':BEGIN
        '''ECHO Hey there! This process to activate sql servises upen stopping... 
        ''':END
        '''@ECHO OFF
        ''':BEGIN
        '''ECHO  Powered By Ahmed Rashwan-Ocean Soft technical support!
        ''':END
        '''color 1b
        '''net start MSSQLSERVER /y
        '''net Start SQLSERVERAGENT /y
        '''net Start SQLBrowser /y.
        '''</summary>
        Public ReadOnly Property Startserv() As String
            Get
                Return ResourceManager.GetString("Startserv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @ECHO OFF
        ''':BEGIN
        '''ECHO Hey there! This process to stop sql servises ... 
        ''':END
        '''@ECHO OFF
        ''':BEGIN
        '''ECHO  Powered By Ahmed Rashwan-Ocean Soft technical support!
        ''':END
        '''color 1b
        '''net stop MSSQLSERVER /y
        '''net stop SQLSERVERAGENT /y
        '''net stop SQLBrowser /y.
        '''</summary>
        Public ReadOnly Property Stopserv() As String
            Get
                Return ResourceManager.GetString("Stopserv", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
